- name: Запустить тест Wialon
        env:
          WIALON_TOKEN: ${{ secrets.WIALON_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python test_wialon.py
